schema_version = "1.0.0"

id = "keymesh"
version = "2.3.2"
name = "Keymesh"
tagline = "Create stop-motion animations by sculpting frame-by-frame"
maintainer = "Nika Kutsniashvili <nickberckley@gmail.com>"
type = "add-on"

website = "https://blenderartists.org/t/keymesh/"
tags = ["Animation", "Sculpt", "Mesh"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/is suppose to dolicenses/
# use "SPDX: prefix.
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2024 Nika Kutsniashvili",
  "2024 Pablo Dobarro",
  "2024 Daniel Martinez Lara",
  "2024 Aldrin Mathew",
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".*",
]

[permissions]
files = "Store generated pose preview images and/or load them from disk"
